nordicopen/easee_hass

- custom_components/easee/sensor.py
This PR will remove unused entries after option changes
> Clean up unused entities

- custom_components/easee/config_flow.py
- custom_components/easee/const.py
- custom_components/easee/entity.py
- custom_components/easee/sensor.py
- custom_components/easee/translations/en.json
Adding unit selection to config flow and let user select between kW/W and kWh/Wh. Moved some variables to const too.
> Unit selection

- custom_components/easee/const.py
Removed a switch_func that was in maxCurrent and shouldn't be, came from testing :)
> Bugfix const

- custom_components/easee/const.py
- custom_components/easee/sensor.py
Using HA const for units as applicable + make lint.
> Use HA const

- custom_components/easee/__init__.py
- custom_components/easee/config_flow.py
- custom_components/easee/const.py
Updates from work on official component 
- removing bug resulting in "malformed user input"
- fix error when changing options
- improved schedule sensor
> Bugfix and improvements

- custom_components/easee/const.py
Rename several sensors to snake_case from camelCase.
Breaking change, modified sensors must be re-added from integration options.
> Rename sensors to snake_case

- custom_components/easee/__init__.py
Services seems to have been lost during the clean-up of __init__.py when fixing unload stuff. Re-adding as it was.
> re-add services

- custom_components/easee/manifest.json
- custom_components/easee/services.py
- custom_components/easee/services.yaml
This service used together with with device tracker can be used to open you charger when you home and require rfid or whitelist when you not.
Using this service will also stop and start the charge when the access is changed.
> Add access_level service.

- custom_components/easee/binary_sensor.py
- custom_components/easee/const.py
- custom_components/easee/controller.py
Add class for binary sensors and convert the entities that fits this platform. Based on 'controller_rewrite' branch to fit new controller structure.
> Add binary sensors

- custom_components/easee/config_flow.py
- custom_components/easee/translations/en.json
- custom_components/easee/translations/sv.json
> Remove unnecessary code and add swedish language

- custom_components/easee/__init__.py
- custom_components/easee/config_flow.py
- custom_components/easee/entity.py
- custom_components/easee/translations/en.json
- custom_components/easee/translations/sv.json
Still a few things to clean up after change of options. But that is WIP.
> Fix crash on setting options after initial install

- INFO.md
- README.md
- custom_components/easee/__init__.py
Removing unnecessary code and update readme text
> Remove remnants of yaml config

- custom_components/easee/translations/nb.json
> Norwegian translation

- custom_components/easee/config_flow.py
Fix error when setting options first time after fresh install of the integration
> Make set options work after fresh install

- custom_components/easee/entity.py
We mix state.something and other_someething else. Replace all dots with underscore like home assistant devs recommends.
> replace . with _ in all attributes keys

- custom_components/easee/const.py
Resolve merge conflict, replacing #75
> Hellowlol main fuse

- Makefile
- custom_components/easee/__init__.py
- custom_components/easee/binary_sensor.py
- custom_components/easee/config_flow.py
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/sensor.py
- custom_components/easee/switch.py
- requirements-dev.txt
- setup.cfg
Add isort to lint target in Makefile and process all .py files
> Sort imports according to HA requirements

- Makefile
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/manifest.json
- setup.cfg
Further consolidation of charger and equalizer to recude code duplication.
latestPulse workaround removed since new library solves this in a better way.
Bump library revision.
> Code consolidation and latestPulse fix.

- custom_components/easee/manifest.json
- custom_components/easee/system_health.py
- custom_components/easee/translations/en.json
- links.sh
Add a few lines of integration health data to Info panel. Chose to not translate strings here in line with what others do.
> Add system health info

- custom_components/easee/services.py
- custom_components/easee/services.yaml
Adding a service for setting offline limit. Must be tested (and merged) with with corresponding [PR#47 on lib](https://github.com/fondberg/pyeasee/pull/47)
> Service for offline limit

- custom_components/easee/manifest.json
- Fix to satisfy hassfest - and upcoming HA release
> Add iot_class to manifest.json

- custom_components/easee/services.py
- custom_components/easee/services.yaml
> Fix smart charging service call

- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- hacs.json
HA 2021.9 changes behaviour of e.g. energy sensors. The `last_reset attribute` is replaced by a new state class - `STATE_CLASS_TOTAL_INCREASING`. The change is not backwards compatible with previous versions of HA.
Fixes #141 #138
> Implement sensor class TOTAL_INCREASING

- custom_components/easee/binary_sensor.py
- custom_components/easee/entity.py
- custom_components/easee/sensor.py
Reverts fondberg/easee_hass#146
> Revert "Add configuration_url to device_info"

- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/manifest.json
- custom_components/easee/services.py
- custom_components/easee/switch.py
Check if site_state is None before calling its functions.
Add an attribute to online sensors that signals if the signalr stream is connected.
Before calling any API that changes a current limit verify that it is an actual change and skip calling the API if not needed.
Improved error handling in service calls.
> Error handling, signalr state and check limit calls before calling API

- custom_components/easee/diagnostics.py
Add diagnostics download capability.
More data sets can easily be added.
> Add support for diagnostics download

- custom_components/easee/config_flow.py
The un-selecting of monitored sites did not work fully the first time after installation of the integration. Fixes #160
> Corrected initial selection of monitored sites

- Makefile
- custom_components/easee/const.py
- custom_components/easee/diagnostics.py
- custom_components/easee/manifest.json
- setup.cfg
> Bump dependency, version and lint

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/new_bug_form.yml
- .github/ISSUE_TEMPLATE/support.yml
Better structure to issues and feature requests. In the best of worlds this can avoid a few immediate requests for more information.
> New issue forms

- custom_components/easee/const.py
- hacs.json
Update code to HA recommendations to avoid future deprecation warnings
> Use enums instead of str constants

- custom_components/easee/entity.py
Use the short form `_attr_` for properties where applicable. Results in some 30 lines of code less.
> Use _attr_* for static properties

- custom_components/easee/services.py
- custom_components/easee/services.yaml
- custom_components/easee/translations/en.json
Follow up PR to #223 
- Refactoring of validation schemas to a more structured approach
- Use constants for limits in schemas
- And more minor things
> Structure of schemas and misc small fixes

- custom_components/easee/services.py
- custom_components/easee/services.yaml
- custom_components/easee/translations/en.json
Build structured schemas for services to reduce duplication of code
> Schema structure in services

- custom_components/easee/manifest.json
Change to new lib with boolean bug fix
> Bump pyeasee lib to 0.7.46

- INFO.md
- README.md
> Add info about services and some minor adjustments

- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/services.py
- custom_components/easee/services.yaml
Some updates to descriptions in services.yaml.
Changes as suggested by lint.
> Some changes to service descriptions in services.yaml + lint

- custom_components/easee/manifest.json
Enable upcoming features in Home Assistant
> Add new keys to manifest.json

- custom_components/easee/manifest.json
> Bump pyeasee version

- custom_components/easee/services.py
- custom_components/easee/services.yaml
Make stop-datetime an optional argument to Set Basic Charge Plan
Fixes #259
> Make stop datetime optional in set_basic_charge_plan

- custom_components/easee/__init__.py
- custom_components/easee/const.py
- custom_components/easee/entity.py
Use UnixOfXX enums instead of plain constants.
PR also includes a few pylint adjustments
> Use UnitOfPower etc instead of plain constants

- custom_components/easee/__init__.py
- custom_components/easee/const.py
Set MIN_HA_VERSION in const.py when new HA features are added.
> Enforce minimum HA version

- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/manifest.json
Slave chargers does not provide the data needed for the circuit_current sensor, so it will not be created for slave chargers.
> Do not create circuit_current sensor for slave chargers

- custom_components/easee/controller.py
Firmware API has all of a sudden started to return 401 error.
Adding checks in code to allow integration to start despite of this.
> Firmware API not working anymore.

- custom_components/easee/binary_sensor.py
- custom_components/easee/controller.py
- custom_components/easee/sensor.py
- custom_components/easee/switch.py
> Async improvements

- custom_components/easee/const.py
- custom_components/easee/entity.py
Attempt to fix KeyError in state function.
Does this give us unwanted side-effects?
> Fix for KeyError in state function

- custom_components/easee/const.py
- custom_components/easee/controller.py
Schedules are no longer polled, but instead uses data sent over signalr.
Needs more testing.
> Removed schedule API polling

- custom_components/easee/services.py
- custom_components/easee/services.yaml
Remove code that has been deprecated since 6 months.
> Remove deprecated services

- custom_components/easee/translations/nl.json
Add new status codes, update missed sensor translation.
> More status codes - NL translation

- custom_components/easee/translations/is.json
Added translation file for icelandic
> Added translation file for icelandic

- custom_components/easee/translations/nl.json
Translate no_sites_in_account to Dutch
> Translate NoSites

- custom_components/easee/translations/ro.json
> strings update v01

- custom_components/easee/services.py
- custom_components/easee/services.yaml
New services for setting and deleting weekly schedule added.
> Added support for weekly schedule

- custom_components/easee/const.py
- custom_components/easee/entity.py
- custom_components/easee/manifest.json
Display models "Easee Home", "Easee Charge" and "Charge Lite". Upcoming models "Charge Core" and "Charge Max" will be added as soon as the codes are available.
> Show product model on device info page

- custom_components/easee/entity.py
- custom_components/easee/services.yaml
A few bugs appeared when an Equalizer was present.
> Fixes for product_code

- custom_components/easee/services.py
Easee API uses UTC time zones, service for setting weekly schedule did not.
> Fixing timezone issues

- custom_components/easee/__init__.py
- custom_components/easee/binary_sensor.py
- custom_components/easee/config_flow.py
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/sensor.py
- custom_components/easee/services.py
- custom_components/easee/switch.py
All recommendations from ruff are taken care of.
> Run ruff on all files

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/release-drafter.yml
- INFO.md
- README.md
- custom_components/easee/manifest.json
References to fondberg as repo owner are changed to nordicopen
> Move from fondberg to nordicopen

- .devcontainer.json
- requirements-devcontainer.txt
- requirements.txt
> Adjust dev container

- custom_components/easee/binary_sensor.py
- custom_components/easee/const.py
- custom_components/easee/entity.py
- custom_components/easee/sensor.py
- hacs.json
Requires HA v 2023.11.0 or later.
> Show serial number on device page

- custom_components/easee/const.py
- custom_components/easee/controller.py
Poll equalizer import and export energy at a random time after each hour mark, tro try an remedy missing data in HA energy panel
> Equalizer poll after hour mark

- custom_components/easee/__init__.py
Move code from async_setup() to async_setup_entry() to make hassfest validation happy.
> Remove async_setup()

- custom_components/easee/services.py
Previous fix had a side effect causing set_circuit_max_limit to malfunction
> set_circuit_max_limit problem

- INFO.md
Update readme for HACS to show active maintenance.
> Fix maintenance tag in HACS

- Makefile
- custom_components/easee/const.py
- custom_components/easee/manifest.json
- hacs.json
- setup.cfg
Bump version and update minimum HA version
> Bump version to 0.9.59

- custom_components/easee/config_flow.py
- custom_components/easee/controller.py
- custom_components/easee/manifest.json
> Add integration version to user-agent header

- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/manifest.json
- custom_components/easee/services.py
- custom_components/easee/services.yaml
- custom_components/easee/translations/en.json
- custom_components/easee/translations/sv.json
New service to control surplus charging modes.
New service to control charger phase mode.
New services to enable/disable schedules without changing them.
Current limit added as option to schedule settings services.
> Service updates

- .devcontainer.json
- scripts/setup
Install libpcap and libturbojpg to get prevent startup errors
Make zsh default shell
> Tweak devcontainer

- custom_components/easee/binary_sensor.py
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/services.py
- custom_components/easee/services.yaml
- custom_components/easee/switch.py
- custom_components/easee/translations/en.json
Change binary sensors for schedule and surplus charging to switches.
Change name of surplus charing service from set_load_balancing to set_surplus_charging.
Requires updated pyeasee.
> Binary sensors change to switches, change service name.

- custom_components/easee/controller.py
> Change deprecated async_timeout to asyncio.timeout

- custom_components/easee/__init__.py
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- Changed to use builtin unload helper when creating trackers
- Remove some stale and unnecessary code
> Cleanup cleanup code

- .pylintrc
- custom_components/easee/binary_sensor.py
- custom_components/easee/button.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/sensor.py
- custom_components/easee/switch.py
Update async method names to align with convention, i.e. async_do_something()
> Async names and improved typing

- Makefile
- custom_components/easee/const.py
- custom_components/easee/manifest.json
- setup.cfg
> BumpPyeaseeAndRelease

- .gitignore
- custom_components/easee/const.py
- custom_components/easee/controller.py
- custom_components/easee/entity.py
- custom_components/easee/light.py
- custom_components/easee/translations/en.json
- links.sh
Represent LED strip brightness as a light entity
Easee app sets the value to 25, 50, 75, and 100%. However it accepts and reports back intermediate integer values also.
Requires updated pyeasee lib
> Represent LED strip brightness as a light entity

- .devcontainer.json
- .github/workflows/python-app.yml
- .pre-commit-config.yaml
- .ruff.toml
Update the devcontainer to use python 3.13. Also a few adjustments to other tools in the container.
> Update devcontainer to python 3.13

- custom_components/easee/config_flow.py
Fixes a deprecation warning that appears when using the options flow for selecting sites to monitor.
> Fix deprecation warning

- custom_components/easee/services.py
- custom_components/easee/services.yaml
- custom_components/easee/translations/en.json
Add a service to enable/disable local OCPP mode.
> Add OCPP mode service

- hacs.json
Update minimum HA version to 2025.7.0
> Update min HA version
