nordicopen/easee_hass

custom_components/easee/sensor.py
links.sh

The units for the energy sensors are changed to Wh (since that is the unit for energy, not W as was previously used, which is a unit for power).
The power sensor now has attributes where currents and voltages are visible.
Background information:
Seems like the nomenclature used by easee API is:
T1 = terminal 1, normally connected to PE (protective ground).
T2 = terminal 2, can either be connected to N (neutral) or L1 (phase 1) depending on what type of electric system it is connected to.
T3 = terminal 3, L1 or L2 depending on electric system.
T4 = terminal 4, L2, L3 or nothing depending on electric system.
T5 = terminal 5, L3 or nothing depending on electric system.
So on a 3-phase system as in Sweden, T1 = PE, T2 = N, T3 = L1, T4 = L2, T5 = L3.
Which means inCurrentT2 will be the current …

Change energy unit to Wh and add voltage/current attributes to power sensor.

---

custom_components/easee/sensor.py

Seems like Easee API returns null at some point for the circuitTotalPhaseConductorCurrentL1/L2/L3 which leads to exceptions due to the max() and round_2_dec() functions used in our setup. Didn't get this in the start, but appears repeatedly in my logs now. The null value successfully becomes None, so implemented a check to set 0.0 if state is None.

Fixing circuit current returning null

---

custom_components/easee/const.py

For some reason Easee doesn't show cableLocked when lockCablePermanently is on (and thus locked). So adding an or to the state condition to make sure HA shows locked if it is either locked or permanently locked.

fix cable locked sensor

---

custom_components/easee/sensor.py

Bummer. The units for consumption sensors suddenly became Amps (or last data["unit"] from last for-loop). Hardcoding as kWh as default when checking for custom units.

Bugfix units consumption sensors

---

custom_components/easee/const.py

Split into cableLockedCar (sensor) and cablePermanentlyLockedCharger (switch).
In my experience, the cableLocked refers to and is decided by the car, while the cablePermanentlyLocked refers to and is decided by the charger. Splitting into to entities, one sensor (we cannot use switch for what the car decides) and one switch (wheter the cable is permanetly locked to charger or not, as per Easee app).

Split locked cable and permanently locked cable

---

custom_components/easee/const.py
custom_components/easee/entity.py

States and attributes for voltages power/energy and current are displayed with 0 or 1 decimal places. However the frontend will strip trailing zeroes i attributes.

Set decimal places for states and attributes

---

custom_components/easee/const.py
custom_components/easee/entity.py
custom_components/easee/translations/sensor.en.json
custom_components/easee/translations/sensor.nb.json
custom_components/easee/translations/sensor.sv.json

Sensor status can now be localized so "CHARGING" is "Charging" in english and "Laddar" in swedish. Bokmål remains to be fixed.

Localize status sensor

---

custom_components/easee/const.py

as this is set to true if the has been locked to rfid using the app or the set_access service.
This way we can check if the chargerbot is really paused or it its paused waiting for auth.

Add config.authorizationRequired

---

custom_components/easee/__init__.py
custom_components/easee/config_flow.py
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/manifest.json
custom_components/easee/sensor.py
custom_components/easee/translations/en.json
custom_components/easee/translations/nb.json
custom_components/easee/translations/sv.json

Improved handling of the unselecting of entities and the following cleanup.
I cannot verify that it works for eq-sensors since I don't have access to an Equalizer.

Clean removal of entities

---

custom_components/easee/const.py

This small tweak creates an optional sensor that reads the "lifetimeEnergy" attribute from the chargerstate. This is useful for someone that wants to track costs via the HASS Utility Meter and Template Sensors as this value does not reset and only counts up.

Add Lifetime Energy Consumption Sensor

---

custom_components/easee/controller.py

A patch that aims to keep track of when a charger/equalizer goes offline/online and/or if the cloud API does not respond.

Keep track of online status of charger/equalizer and/or cloud

---

.github/workflows/hassfest.yaml
INFO.md
Makefile
README.md
custom_components/easee/const.py
custom_components/easee/manifest.json
custom_components/easee/translations/sensor.en.json
custom_components/easee/translations/sensor.nb.json
custom_components/easee/translations/sensor.sv.json

Added github action to validate custom_component with hassfest.
Fixed warnings that hassfest revealed:
- Add version string to manifest.json - soon to be mandatory
- Update makefile/bumpversion
- Fix names of custom device_classes
https://developers.home-assistant.io/blog/2020/04/16/hassfest
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/

Validation with hassfest

---

custom_components/easee/__init__.py
custom_components/easee/binary_sensor.py
custom_components/easee/config_flow.py
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/sensor.py
custom_components/easee/switch.py
custom_components/easee/translations/sensor.en.json
custom_components/easee/translations/sensor.nb.json
custom_components/easee/translations/sensor.sv.json

Equalizer "status" sensor change name to "online" to better match the charger sensors.
Equalizer "online" sensor changed to binary_sensor.
Code cleanup that enables more code sharing between charger and equalizer sensors. As a result, the unique IDs of the equalizer sensors had to change, making this a breaking change.
Race condition fix, the schedulers for sensor updates are not started from __init.py__ file anymore, but instead by a call-back when all entities have been created.
Microseconds removed from latestPulse timestamp.

Binary sensor for equalizer, cleanup

---

custom_components/easee/const.py
custom_components/easee/entity.py
custom_components/easee/manifest.json
custom_components/easee/services.py
custom_components/easee/services.yaml
custom_components/easee/translations/sensor.sv.json

All current limits are now called limits instead of current.
in_current is now called current.
cable_locked_car is now called cable_locked.
cable_permanently_locked_charger is now called permanent_cable_lock.
Small swedish translation change.
Adding support for entity_registry_enabled_default to prepare for future support for disabled sensors at first install.

Sensor name changes

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Adding release-drafter workflow. A draft changelog for the next release will be created automatically when a PR is merged with master. Depending on which labels are attached to the PR the items will be sorted under a heading, e.g. bugfix, new features etc. There is also an autolabeler function that assigns bugfix label to a PR if it contains "fix" in the title.
Quite slick!

Release-drafter workflow

---

custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/sensor.py

Adds support for long-term statistics and use of power and energy sensors in energy panel. Addresses issues #129 #130 .
Note that HA currently(2021.8) accumulates data for a limited set of device_classes. Power and accumulated energy sensors are supported. Voltage and current are not supported.
Data will not be displayed until after approximately two hours of data collection.  
Power and energy sensors for Equalizer are split up in separate sensors for import and export. This simplifies the use of these sensors in the energy module. Users that use the old power or energy sensors or their attributes in automations or template sensors should review and modify the configuration.

Add support for long-term statistics and energy module

---

custom_components/easee/binary_sensor.py
custom_components/easee/entity.py
custom_components/easee/sensor.py

New feature in HA 2021.11
Display "Visit Device" link on device info page. Points at "My Products" in Easee cloud.

Add configuration_url to device_info

---

custom_components/easee/__init__.py
custom_components/easee/binary_sensor.py
custom_components/easee/config_flow.py
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/sensor.py
hacs.json

All available entities are now created but only a selection based on `enabled_default` in const.py are enabled by default. The user can activate or deactivate the entities in the device info page.
- Migrate current options settings on first run of this version
- Remove monitored conditions from options page
- Remove monitored conditions from config_entry
- Decide on which sensors should be enabled by default
- Decide on enity_category for each entity - only valid from HA 2021.11

Rework entity creation

---

custom_components/easee/manifest.json
custom_components/easee/services.py

Fix typo ('serive') and add name of service that fails in addition to the service data that is there before.

Improve error logging for services

---

custom_components/easee/controller.py

The current limit compare functions was not working if the compare value is a config value rather than a state value.

Fix for current limit compare not working

---

custom_components/easee/const.py

The use of ENTITY_CATEGORY_* constants is deprecated and will start to generate warnings from HA 2022.2 
This PR uses EntityCategory.* enums instead.

Change to EntityCategory

---

custom_components/easee/config_flow.py
custom_components/easee/translations/en.json
custom_components/easee/translations/nb.json
custom_components/easee/translations/sv.json

If the user's account contains more than one site the config flow will now open a second form that offers the possibility to select which sites that should be monitored.
This is a more intuitive flow where most users don't need to go back to "Configure" after initial setup.
Ref FR in #160 by @skela

Let user select sites during initial setup

---

.github/release-drafter.yml
.github/workflows/release.yml
INFO.md
README.md
hacs.json

Add download counters to the repo. 
The download counters built into Github requires that the downloads are packaged in "assets". This is done in the workflow relase.yml. A subsequent requirement is that HACS must download this asset. This is flagged in hacs.json.
The counter will just show zero until next release of easee_hass

Add download counters to repo

---

hacs.json

Require >= HA 2022.2
Integration will crash if installed on earlier versions of HA
Fixes #170

Bump version i hacs.json

---

custom_components/easee/controller.py
custom_components/easee/diagnostics.py

When Easee ready backplates are included in an installation, they will show up as chargers without a valid ID or name.
A check for this is added to the code.
Debug data with site information is also added to the diagnostics data download.

Fix for empty backplates, diagnostics improvement.

---

custom_components/easee/config_flow.py

Clean up config if a site is deleted or renamed on the Easee cloud service.
The user must still reload the integration or restart HA in order to discover the new site.
Fixes #168

Handle deleted sites

---

custom_components/easee/entity.py
custom_components/easee/sensor.py

Sensors should report `native_value` and `native_unit_of_measurement` instead of deprecated `state` and `unit_of_measurement`. This is to enable centralized conversion of values for presentation in the UI. Today (HA 2022.4) this feature is implemented for e.g. temperature, pressure and distance but so far not for power (W/kW) or energy (Wh/kWh).

Change to native_value for sensors

---

custom_components/easee/controller.py
hacs.json

When the easee servers are malfunctioning, it seems that it is sometimes possible to login but not use the other API functions. This was badly handled in the code and this should improve that.
Also removes some deprecated data from hacs.json.

Improve startup robustness

---

custom_components/easee/controller.py

Getting charger state and config separately since site state API has stopped returning them.

Fix for site state API change

---

custom_components/easee/entity.py

Adapt to new entity naming model. 
The construction of entity names is transferred to core. The resulting entity names should be the same as in our current code. Thus no breaking change.
For background please refer to https://developers.home-assistant.io/blog/2022/07/10/entity_naming

Change to new entity naming model

---

custom_components/easee/controller.py

Currently the schedules are polled on a regular basis. This patch limits the polling to when the schedule is changed (as signalled by the signalr stream data).

Remove unecessary polling of schedules.

---

custom_components/easee/config_flow.py
custom_components/easee/controller.py

Changed calls to get_sites to get_account_products since the latter returns only the sites/products that are accessible by the logged in user and therefore avoids a lot of non functioning entities in large installations (hopefully).

Large site fixes

---

custom_components/easee/controller.py

A call to get_site_state was left in the code, but not actually used anymore.

Remove unnecessesary call to get_site_state.

---

custom_components/easee/sensor.py

The cost sensors do not report a currency symbol if there is no charging session during the respective period.
This fix will add the currency symbol set up for the site if none is reported by API.
Before: 0
Now: 0.00 EUR

Always display currency symbol if set on site

---

custom_components/easee/controller.py
custom_components/easee/manifest.json
custom_components/easee/services.py
custom_components/easee/switch.py

Only `site_admin` or `site_owner` are allowed to toggle some switches. If the authenticated user is a `site_user` a 403-Forbidden is returned.
This PR tries to handle this situation. It requires an updated lib that can raise `ForbiddenServiceError` exceptions.

Improved handling of 400 and 403 responses

---

custom_components/easee/__init__.py
hacs.json

- Set required HA version to 2023.4.0 in HACS
- Use core routines for setup and unload of entries

Bump required minimum HA version

---

custom_components/easee/__init__.py
custom_components/easee/controller.py

The latestFirmware state had a race condition at startup that is now avoided with this change.
Also, latestFirmware is now polled once per day to check for new firmware.
Asyncio import removed due to not needed and failed lint.

Avoid race condition

---

custom_components/easee/__init__.py
custom_components/easee/config_flow.py
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/translations/en.json
custom_components/easee/translations/sv.json

HA UI can now natively adjust units and precision, so the ability to change this in the integrations configuration was removed.
To facilitate this, some equalizer sensor attributes has been changed in to separate sensors:
Export reactive energy
Import reactive energy
Export reactive power
Import reactive power

Remove option to change units kW/W kWh/Wh

---

custom_components/easee/entity.py

The state of an entity should never be an empty string. This PR will replace empty strings in states with None

Entities return state as None instead of ""

---

custom_components/easee/const.py
custom_components/easee/controller.py

Log error once when firmware api endpoint fails. Make upgrade sewnsor display Unknown when data is unavailable.

Improve error handling around latest firmware API endpoint

---

custom_components/easee/services.py

Seems the datatype of the circuit_id when given as reference in service calls was string and not int which caused it to malfunction.

Fix for circuit_id not working as reference for service calls.

---

custom_components/easee/const.py
custom_components/easee/device_action.py
custom_components/easee/device_condition.py
custom_components/easee/device_trigger.py
custom_components/easee/translations/en.json
links.sh

This PR introduces device_triggers and device_automations to enable the GUI in automations editor for Easee charger devices. The triggers are activated when the selected state is entered irrespective of what the previous state was.
Triggers and conditions are present on device level in the automations editor. I will try to add them also to the status sensor in a follow-up PR.
When this PR is merged, `en.json` should be uploaded to Lokalise to open up for translation to other languages.

Enable device automations

---

custom_components/easee/__init__.py
custom_components/easee/config_flow.py
custom_components/easee/controller.py
custom_components/easee/translations/en.json

If the API password is changed, a request for reathentication will be triggered. The user will just have to enter the new password and thus no need for uninstall/Install in this situation anymore.

Reauthenticate when API password is changed

---

custom_components/easee/const.py

Since slave chargers does not provide correct values for the dynamic_circuit_limit sensors, it is better to remove it.

Remove some non working sensors from slave chargers

---

.pre-commit-config.yaml
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/icons.json
custom_components/easee/services.py

HA recommends using icon translations instead of assigning the icons as entity attributes. Service icons will also soon be mandatory.
Also removed black formatter from .pre-commit-config.yaml since it caused instability in the formatting. It should really have been removed when we went over to ruff.

Add icon translations

---

custom_components/easee/services.yaml

We have to make the device selector to exclude Equalizers from service targets. Previously we used device_class == "monetary" to ensure that only chargers were listed. But if the user diabled all monetary sensors on their charger  no target device could be found. We now change to requiering that the device contains a switch platform. This method cannot be blocked by the user.

Change method for excluding Equalizers

---

.devcontainer.json
.github/workflows/dependabot.yaml
.github/workflows/hassfest.yaml
.github/workflows/python-app.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/validate_hacs.yaml
.pre-commit-config.yaml
.ruff.toml
requirements-devcontainer.txt
requirements.txt

Update dev container to python3.12 as earlier versions are unsupported from HA 2024.4.
Update ruff linter to 3.3 and align rules with HA 2024.4

Update dev env to python3.12 and bump dependencies

---

Makefile
custom_components/easee/const.py
custom_components/easee/manifest.json
setup.cfg

pyeasee 0.8.4: workaround for signalr lib reconnect issue.

New version of pyeasee and bump version

---

custom_components/easee/button.py
custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/icons.json
custom_components/easee/translations/en.json

Add a button entity for executing the override_schedule action command from the UI.
Additional buttons can easily be created for remaining action commands if desired.

Add button entity for override_schedule action

---

custom_components/easee/const.py

After the change of basic_schedule and weekly_schedule from binary_sensor to switch it is more logical to put them in EntityCategory.CONFIG.

Change EntityCategory to CONFIG

---

custom_components/easee/controller.py
custom_components/easee/entity.py
custom_components/easee/services.py

Changed the old scheme of updating all entities when a change occurred to now only updating the entities that has changed data. Realised through by allowing the entities to register for updates on specific data, and when those change, send an update request/callback.
Some unnecessary polling removed.

Product data reworked to send out notifications to registered change listeners

---

custom_components/easee/const.py
custom_components/easee/controller.py
custom_components/easee/translations/en.json

Sensor energy_per_hour changed name changed to energy_last_hour and disabled by default to hopefully cause less confusion about what it means/does.
A few more diagnostic attributes added to charger online sensor.

Changes to sensor configs

---

custom_components/easee/light.py

Brightness value may not be available early during startup.

Guard brightness until value is populated

---

custom_components/easee/controller.py
custom_components/easee/manifest.json

Delays and collects updates in to call for all chargers on a site.

CostData class for handling of cost updates added

---

custom_components/easee/controller.py

Since the cost polling API has 10 calls/hour limit, we need to make sure not to call it more often than every 20 minutes (given that we make 3 calls every time we call).
This also changes the implementation to use asyncio.queue instead of dqueue.

Cost refresh updated to comply with 10 calls per hour limit

---

custom_components/easee/controller.py

I got an annoying error from `pyeasee.easee` that keep going for some times now.
```
AttributeError: 'HassLogger' object has no attribute 'print'
```
This PR replace the only  `_LOGGER.print` from the project to `_LOGGER.debug`

fix: Logger has no method print
